apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argocd
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  generators:
  - git:
      files:
      - path: '*/configurations/*/cluster-config.yaml'
      repoURL: 'https://github.com/gmarcy/homelab-argocd.git'
      requeueAfterSeconds: 20
      revision: ""
      template:
        metadata: {}
        spec:
          destination: {}
          project: ""
  syncPolicy: {}
  template:
    metadata:
      name: '{{ cluster.name }}-{{ app.name }}'
      namespace: argocd
      labels:
        app.kubernetes.io/name: '{{ app.label }}'
    spec:
      destination:
        namespace: '{{ destination.namespace }}'
        server: '{{ destination.server }}'
      ignoreDifferences:
      - group: argoproj.io
        jsonPointers:
        - /status
        kind: Application
      - group: apps
        jsonPointers:
        - /spec/replicas
        kind: Deployment
      project: '{{ project.name }}'
      source:
        path: '{{ source.path }}'
        repoURL: '{{ source.repoURL }}'
        targetRevision: '{{ source.targetRevision }}'
        plugin:
          name: kustomize-build-with-helm-and-avp
          env:
          - name: AVP_TYPE
            value: kubernetessecret
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
          - RespectIgnoreDifferences=true
        automated:
          allowEmpty: true
          prune: true
          selfHeal: true
