apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
  - application-set.yaml
  - homelab-project.yaml
  - ingress.yaml
  - namespace.yaml

configMapGenerator:
  - behavior: merge
    literals:
      - timeout.reconciliation="30s"
    name: argocd-cm
  - behavior: merge
    literals:
      - server.insecure="true"
    name: argocd-cmd-params-cm
