app:
  label: grafana-agent
  name: grafana-agent
cluster:
  name: nuc10-cluster
destination:
  namespace: grafana-agent
  server: https://192.168.222.214.nip.io:6443
project:
  name: default
source:
  path: grafana-agent/overlays/nuc10-cluster
  repoURL: https://github.com/gmarcy/homelab-argocd.git
  targetRevision: HEAD
