apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- certificates/issuer-matchbox-rpc-ca.yaml
- certificates/issuer-matchbox-rpc.yaml
- certificates/matchbox-rpc-ca.yaml
- certificates/matchbox-rpc-selfsign.yaml
- deployment.yaml
- ingress.yaml
- namespace.yaml
- service.yaml
