apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: awx

resources:
  - ingress.yaml
  - namespace.yaml

helmCharts:
  - name: awx-operator
    repo: https://ansible.github.io/awx-operator/
    releaseName: awx-operator
    namespace: awx
    version: 2.9.0
    includeCRDs: true
    valuesInline:
      AWX:
        enabled: true
