apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- certificates/issuer-mutatingwebhook.yaml
- certificates/issuer-webhook-ca.yaml
- certificates/webhook-ca.yaml
- certificates/webhook-selfsign.yaml
- controller/clusterrolebindings.yaml
- controller/clusterrole-external-provisioner-runner.yaml
- controller/clusterrole-external-resizer-runner.yaml
- controller/clusterrole-external-snapshotter-runner.yaml
- controller/clusterroles.yaml
- controller/crb-csi-provisioner-role.yaml
- controller/crb-csi-resizer-role.yaml
- controller/crb-csi-snapshotter-role.yaml
- controller/csidriver.yaml
- controller/deployment.yaml
- controller/poddisruptionbudget.yaml
- controller/rb-csi-resizer-role-cfg.yaml
- controller/role-binding-csi-provisioner-role-cfg.yaml
- controller/rolebinding-external-snapshotter-role-cfg.yaml
- controller/rolebinding-leader-election.yaml
- controller/role-external-provisioner-cfg.yaml
- controller/role-external-resizer-cfg.yaml
- controller/role-external-snapshotter-cfg.yaml
- controller/role-leader-election.yaml
- controller/serviceaccount.yaml
- controller/service.yaml
- lvmd/configmap.yaml
- lvmd/daemonset.yaml
- lvmd/serviceaccount.yaml
- node/clusterrolebinding.yaml
- node/clusterrole.yaml
- node/daemonset.yaml
- node/serviceaccount.yaml
- crd.yaml
- mutatingwebhook.yaml
- namespace.yaml
- priorityclass.yaml
- storageclass-local-provisioner.yaml
- storageclass.yaml