apiVersion: operator.open-cluster-management.io/v1
kind: ClusterManager
metadata:
  name: cluster-manager
spec:
  deployOption:
    mode: Default
  #registrationConfiguration:
  #  featureGates:
  #  - feature: DefaultClusterSet
  #    mode: Enable
