app:
  label: openshift-console
  name: console
cluster:
  name: nuc10-cluster
destination:
  namespace: openshift-console
  server: https://192.168.222.214.nip.io:6443
project:
  name: default
source:
  path: console/overlays/nuc10-cluster
  repoURL: https://github.com/gmarcy/homelab-argocd.git
  targetRevision: HEAD
