apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml

helmCharts:
  - name: external-secrets
    repo: https://charts.external-secrets.io/
    releaseName: external-secrets
    namespace: external-secrets
    version: 0.9.11
    valuesInline:
      certManager:
        enabled: true
        cert:
          issuerRef:
            name: "cluster-issuer"
