app:
  label: openshift-console
  name: console
cluster:
  name: nuc8-cluster
destination:
  namespace: openshift-console
  server: https://kubernetes.default.svc
project:
  name: default
source:
  path: console/overlays/nuc8-cluster
  repoURL: https://github.com/gmarcy/homelab-argocd.git
  targetRevision: HEAD
