---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: netbootxyz-assets
  namespace: netbootxyz
  labels:
    app: "netbootxyz"
    app.kubernetes.io/instance: "netbootxyz"
    app.kubernetes.io/name: "netbootxyz"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: netbootxyz-config
  namespace: netbootxyz
  labels:
    app: "netbootxyz"
    app.kubernetes.io/instance: "netbootxyz"
    app.kubernetes.io/name: "netbootxyz"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
