appName: ingress-nginx
userGivenName: ingress-nginx
destNamespace: default
destServer: https://192.168.222.253.nip.io:6443
srcPath: apps/ingress-nginx
srcRepoURL: https://github.com/gmarcy/homelab-argocd.git
srcTargetRevision: ''
labels: null
annotations: null
