app:
  label: ingress-nginx
  name: ingress-nginx
cluster:
  name: argocd-cluster
destination:
  namespace: ingress-nginx
  server: https://kubernetes.default.svc
project:
  name: default
source:
  path: ingress-nginx/overlays/argocd-cluster
  repoURL: https://github.com/gmarcy/homelab-argocd.git
  targetRevision: HEAD
