apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../apps/netbootxyz

patches:
  - patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: netbootxyz.192.168.222.214.nip.io
    target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: netbootxyz
  - patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: netbootxyz-assets.192.168.222.214.nip.io
    target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: netbootxyz-assets
