apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: argocd.192.168.222.214.nip.io
      - op: add
        path: /spec/tls/0/hosts/-
        value: "argocd.192.168.222.214.nip.io"
    target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
  - patch: |-
      - op: replace
        path: /spec/generators/0/git/files/0/path
        value: "*/configurations/nuc10-cluster/cluster-config.yaml"
    target:
      group: argoproj.io
      version: v1alpha1
      kind: ApplicationSet
