app:
  label: dnsmasq-dhcp
  name: dnsmasq-dhcp
cluster:
  name: nuc10-cluster
destination:
  namespace: dnsmasq-dhcp
  server: https://kubernetes.default.svc
project:
  name: homelab
source:
  path: dnsmasq-dhcp/overlays/nuc10-cluster
  repoURL: https://github.com/gmarcy/homelab-argocd.git
  targetRevision: HEAD
