app:
  label: dnsmasq-dhcp
  name: dnsmasq-dhcp
cluster:
  name: nuc10-cluster
destination:
  namespace: dnsmasq-dhcp
  server: https://192.168.222.214.nip.io:6443
project:
  name: default
source:
  path: dnsmasq-dhcp/overlays/nuc10-cluster
  repoURL: https://github.com/gmarcy/homelab-argocd.git
  targetRevision: HEAD
