app:
  label: adguard
  name: adguard
cluster:
  name: netsvcs-cluster
destination:
  namespace: adguard
  server: https://kubernetes.default.svc
project:
  name: default
source:
  path: adguard/overlays/netsvcs-cluster
  repoURL: https://github.com/gmarcy/homelab-argocd.git
  targetRevision: HEAD
