app:
  label: metrics-server
  name: metrics-server
cluster:
  name: no-cluster
destination:
  namespace: metrics-server
  server: https://192.168.222.xxx.nip.io:6443
project:
  name: default
source:
  path: metrics-server/overlays/no-cluster
  repoURL: https://github.com/gmarcy/homelab-argocd.git
  targetRevision: HEAD
