apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - patch: |-
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: "--interface=eno1"
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: "--interface=enp57s0u1"
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: "--interface=enp0s20f0u1"
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: "--interface=enp0s20f0u2"
    target:
      group: apps
      version: v1
      kind: Deployment
