apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - patch: |-
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: "--interface=eno1"
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: "--interface=enp57s0u1"
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: "--interface=enp0s20f0u1"
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: "--interface=enp0s20f0u2"
    target:
      group: apps
      version: v1
      kind: Deployment
  - patch: |-
      - op: add
        path: /spec/options/-
        value:
          key: option:dns-server
          tags:
          - net111
          values:
          - 192.168.111.214
      - op: add
        path: /spec/options/-
        value:
          key: option:dns-server
          tags:
          - net123
          values:
          - 192.168.123.214
      - op: add
        path: /spec/options/-
        value:
          key: option:dns-server
          tags:
          - net222
          values:
          - 192.168.222.214
      - op: add
        path: /spec/options/-
        value:
          key: option:dns-server
          tags:
          - net234
          values:
          - 192.168.234.214
      - op: add
        path: /spec/options/-
        value:
          key: option:tftp-server
          tags:
          - net222
          values:
          - 192.168.222.214
    target:
      group: dnsmasq.kvaps.cf
      version: v1beta1
      kind: DhcpOptions
  - patch: |-
      - op: add
        path: /spec/options/-
        value:
          key: dhcp-boot
          values:
          - tag:net222
          - ipxe/netboot.xyz.efi
          - nuc10
          - 192.168.222.214
      #- op: add
      #  path: /spec/options/-
      #  value:
      #    key: dhcp-match
      #    values:
      #    - set:ipxe
      #    - "175"
      #- op: add
      #  path: /spec/options/-
      #  value:
      #    key: dhcp-boot
      #    values:
      #    - tag:ipxe
      #    - ipxe/netboot.xyz.kpxe
      #- op: add
      #  path: /spec/options/-
      #  value:
      #    key: dhcp-match
      #    values:
      #    - set:efi
      #    - option:client-arch
      #    - "7"
      #- op: add
      #  path: /spec/options/-
      #  value:
      #    key: dhcp-match
      #    values:
      #    - set:efi
      #    - option:client-arch
      #    - "9"
      #- op: add
      #  path: /spec/options/-
      #  value:
      #    key: dhcp-match
      #    values:
      #    - set:efi
      #    - option:client-arch
      #    - "11"
      #- op: add
      #  path: /spec/options/-
      #  value:
      #    key: dhcp-boot
      #    values:
      #    - tag:efi
      #    - tag:!ipxe
      #    - ipxe/netboot.xyz.efi
      #- op: add
      #  path: /spec/options/-
      #  value:
      #    key: dhcp-boot
      #    values:
      #    - tag:net222
      #    - ipxe/netboot.xyz.kpxe
    target:
      group: dnsmasq.kvaps.cf
      version: v1beta1
      kind: DnsmasqOptions
