apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - patch: |-
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: "--base-address=https://console.192.168.222.253.nip.io/"
    target:
      group: apps
      version: v1
      kind: Deployment
  - patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: "console.192.168.222.212.nip.io"
    target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
