app:
  label: matchbox
  name: matchbox
cluster:
  name: netsvcs-cluster
destination:
  namespace: matchbox
  server: https://kubernetes.default.svc
project:
  name: homelab
source:
  path: matchbox/overlays/netsvcs-cluster
  repoURL: https://github.com/gmarcy/homelab-argocd.git
  targetRevision: HEAD
