app:
  label: matchbox
  name: matchbox
cluster:
  name: netsvcs-cluster
destination:
  namespace: matchbox
  server: https://192.168.222.253.nip.io:6443
project:
  name: default
source:
  path: matchbox/overlays/netsvcs-cluster
  repoURL: https://github.com/gmarcy/homelab-argocd.git
  targetRevision: HEAD
