apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: grafana-agent

helmCharts:
  - name: grafana-agent
    repo: https://grafana.github.io/helm-charts
    releaseName: grafana-agent
    namespace: grafana-agent
    version: 0.31.1
    includeCRDs: true
    valuesInline:
      agent:
        ustering:
          enabled: true
