app:
  label: netbootxyz
  name: netbootxyz
cluster:
  name: netsvcs-cluster
destination:
  namespace: netbootxyz
  server: https://kubernetes.default.svc
project:
  name: default
source:
  path: netbootxyz/overlays/netsvcs-cluster
  repoURL: https://github.com/gmarcy/homelab-argocd.git
  targetRevision: HEAD
