app:
  label: netbootxyz
  name: netbootxyz
cluster:
  name: no-cluster
destination:
  namespace: netbootxyz
  server: https://192.168.222.xxx.nip.io:6443
project:
  name: default
source:
  path: netbootxyz/overlays/no-cluster
  repoURL: https://github.com/gmarcy/homelab-argocd.git
  targetRevision: HEAD
