apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ingress-nginx

resources:
  - namespace.yaml
  - service.yaml

helmCharts:
  - name: ingress-nginx
    repo: https://kubernetes.github.io/ingress-nginx/
    releaseName: ingress-nginx
    namespace: ingress-nginx
    version: v4.7.1
    valuesInline:
      fullnameOverride: ingress-nginx
      controller:
        kind: DaemonSet
        hostNetwork: true
        hostPort:
          enabled: true
        ingressClassResource:
          default: true
        service:
          enabled: false
          externalTrafficPolicy: "Local"
        publishService:
          enabled: false
        metrics:
          enabled: false
          serviceMonitor:
            enabled: false
        admissionWebhooks:
          enabled: false
        config:
          use-forwarded-headers: "true"
          enable-ssl-passthrough: "true"
      udp:
        "53": "adguard/adguard-dns:3053"
