apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - clusterissuer.yaml
  - namespace.yaml

helmCharts:
  - name: cert-manager
    repo: https://charts.jetstack.io
    releaseName: cert-manager
    namespace: cert-manager
    version: v1.11.2
    valuesInline:
      installCRDs: true
      global:
        leaderElection:
          namespace: cert-manager

patches:
  - patch: |-
      - op: remove
        path: /metadata/labels/app.kubernetes.io~1instance
    target:
      kind: CustomResourceDefinition
      labelSelector: app.kubernetes.io/instance=cert-manager
