apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - clusterissuer.yaml
  - namespace.yaml
  - secret.yaml

helmCharts:
  - name: cert-manager
    repo: https://charts.jetstack.io
    releaseName: cert-manager
    namespace: cert-manager
    version: v1.11.2
    valuesInline:
      installCRDs: true
      global:
        leaderElection:
          namespace: cert-manager
  - name: homelab-cert-manager-webhook
    repo: https://gmarcy.github.io/helm-charts
    releaseName: homelab-cert-manager-webhook
    namespace: cert-manager
    version: v0.1.0
    valuesInline:
      replicaCount: 1
      image:
        pullPolicy: Always
  - name: homelab-letsencrypt-issuers
    repo: https://gmarcy.github.io/helm-charts
    releaseName: homelab-letsencrypt-issuers
    namespace: cert-manager
    version: v0.1.0
    valuesInline:
      secret: homelab-namecheap-credentials

patches:
  - patch: |-
      - op: remove
        path: /metadata/labels/app.kubernetes.io~1instance
    target:
      kind: CustomResourceDefinition
      labelSelector: app.kubernetes.io/instance=cert-manager
