apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: metallb-system

resources:
  - ../../base

patches:
  - patch: |-
      - op: add
        path: /spec/addresses/-
        value: "192.168.xxx.0/24"
    target:
      group: metallb.io
      version: v1beta1
      kind: IPAddressPool
      name: metallb-addresspool
      namespace: metallb-system
