apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: matchbox

resources:
  - ../../base

patches:
  - patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: matchbox.192.168.222.214.nip.io
    target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: matchbox
