apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: matchbox-rpc-ca
  namespace: matchbox
  labels:
    app.kubernetes.io/name: matchbox
    app.kubernetes.io/instance: matchbox
spec:
  ca:
    secretName: matchbox-rpc-ca
