app:
  label: ingress-nginx
  name: ingress-nginx
cluster:
  name: netsvcs-cluster
destination:
  namespace: ingress-nginx
  server: https://192.168.222.253.nip.io:6443
project:
  name: default
source:
  path: ingress-nginx/overlays/netsvcs-cluster
  repoURL: https://github.com/gmarcy/homelab-argocd.git
  targetRevision: HEAD
