app:
  label: ingress-nginx
  name: ingress-nginx
cluster:
  name: netsvcs-cluster
destination:
  namespace: ingress-nginx
  server: https://kubernetes.default.svc
project:
  name: homelab
source:
  path: ingress-nginx/overlays/netsvcs-cluster
  repoURL: https://github.com/gmarcy/homelab-argocd.git
  targetRevision: HEAD
