app:
  label: argocd
  name: argocd
cluster:
  name: netsvcs-cluster
destination:
  namespace: argocd
  server: https://kubernetes.default.svc
project:
  name: default
source:
  path: argocd/overlays/netsvcs-cluster
  repoURL: https://github.com/gmarcy/homelab-argocd.git
  targetRevision: HEAD
