app:
  label: awx
  name: awx
cluster:
  name: netsvcs-cluster
destination:
  namespace: awx
  server: https://192.168.222.253.nip.io:6443
project:
  name: default
source:
  path: awx/overlays/netsvcs-cluster
  repoURL: https://github.com/gmarcy/homelab-argocd.git
  targetRevision: HEAD
