apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: netbootxyz

resources:
  - ../../base

patches:
  - patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: netbootxyz.192.168.222.253.nip.io
      - op: replace
        path: /spec/tls/0/hosts/0
        value: netbootxyz.192.168.222.253.nip.io
    target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
