appName: cert-manager
userGivenName: cert-manager
destNamespace: cert-manager
destServer: https://kubernetes.default.svc
srcPath: deployments/argocd-cluster/cert-manager
srcRepoURL: https://github.com/gmarcy/homelab-argocd.git
srcTargetRevision: ''
labels: null
annotations: null
