apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: metallb-system

resources:
  - ipaddresspool.yaml
  - l2advertisement.yaml
  - namespace.yaml

helmCharts:
  - name: metallb
    repo: https://metallb.github.io/metallb
    releaseName: metallb
    namespace: metallb-system
    version: 0.13.12
    valuesInline:
      crds:
        enabled: true
