apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: kubevip
    namespace: kube-system
    literals:
      - cidr-global=PATCH_ME
generatorOptions:
  disableNameSuffixHash: true

helmCharts:
  - name: kube-vip
    repo: https://kube-vip.github.io/helm-charts
    releaseName: kube-vip
    namespace: kube-system
    version: 0.4.4
    valuesInline:
      env:
        vip_interface: PATCH_ME
  - name: kube-vip-cloud-provider
    repo: https://kube-vip.github.io/helm-charts
    releaseName: kube-vip-cloud-provider
    namespace: kube-system
    version: 0.2.2
    valuesInline:
