apiVersion: v1
kind: ConfigMap
metadata:
  name: netbootxyz-config
  namespace: netbootxyz
data:
  menu.ipxe: |
    #!ipxe

    chain http://192.168.222.214.nip.io:8080/assets/nbxyz/dualboot.ipxe
  nginx.conf: |
    user abc;
    worker_processes 4;
    pid /run/nginx.pid;
    include /etc/nginx/modules/*.conf;
    events {
        worker_connections 768;
    }
    http {
        sendfile on;
        tcp_nopush on;
        tcp_nodelay on;
        keepalive_timeout 65;
        types_hash_max_size 2048;
        client_max_body_size 0;
        include /etc/nginx/mime.types;
        default_type application/octet-stream;
        access_log /config/log/nginx/access.log;
        error_log /config/log/nginx/error.log;
        gzip on;
        gzip_disable "msie6";
        include /config/nginx/site-confs/*;
    }
    daemon off;
  site-confs.default: |
    server {
        listen 3080;
        location / {
            root /assets;
            autoindex on;
        }
    }
