app:
  label: openshift-console
  name: openshift-console
cluster:
  name: netsvcs-cluster
destination:
  namespace: openshift-console
  server: https://kubernetes.default.svc
project:
  name: default
source:
  path: console/overlays/netsvcs-cluster
  repoURL: https://github.com/gmarcy/homelab-argocd.git
  targetRevision: HEAD
