app:
  label: nmstate
  name: nmstate
cluster:
  name: netsvcs-cluster
destination:
  namespace: nmstate
  server: https://kubernetes.default.svc
project:
  name: default
source:
  path: nmstate/overlays/netsvcs-cluster
  repoURL: https://github.com/gmarcy/homelab-argocd.git
  targetRevision: HEAD
