app:
  label: dnsmasq-dhcp
  name: dnsmasq-dhcp
cluster:
  name: netsvcs-cluster
destination:
  namespace: dnsmasq-dhcp
  server: https://192.168.222.253.nip.io:6443
project:
  name: default
source:
  path: dnsmasq-dhcp/overlays/netsvcs-cluster
  repoURL: https://github.com/gmarcy/homelab-argocd.git
  targetRevision: HEAD
