app:
  label: kube-vip
  name: kube-vip
cluster:
  name: nuc10-cluster
destination:
  namespace: kube-system
  server: https://192.168.222.214.nip.io:6443
project:
  name: default
source:
  path: kube-vip/overlays/nuc10-cluster
  repoURL: https://github.com/gmarcy/homelab-argocd.git
  targetRevision: HEAD
