apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - clusterrole.yaml
  - deployment.yaml
  - ingress.yaml
  - namespace.yaml
  - rolebinding.yaml
  - service-ca.yaml
  - service.yaml
  - serviceaccount.yaml
