kind: ConfigMap
apiVersion: v1
metadata:
  name: service-ca
  namespace: openshift-console
data:
  service-ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDUTCCAjmgAwIBAgIIWbYX7FM9u7owDQYJKoZIhvcNAQELBQAwNjE0MDIGA1UE
    Awwrb3BlbnNoaWZ0LXNlcnZpY2Utc2VydmluZy1zaWduZXJAMTU5NjYyMTg4MTAe
    Fw0yMTA5MDQxMDA0NDZaFw0yMzExMDMxMDA0NDdaMDYxNDAyBgNVBAMMK29wZW5z
    aGlmdC1zZXJ2aWNlLXNlcnZpbmctc2lnbmVyQDE1OTY2MjE4ODEwggEiMA0GCSqG
    SIb3DQEBAQUAA4IBDwAwggEKAoIBAQC4KZ63KRoixxaNVb3rEUaY8d/V1oC8Jm3E
    6VbOTXd4rvBlp96bWCb1P1qs0xLElA6SLjotmJidoTKZH9dygc1GuS0JFN9xJH0b
    aGuZNvcgItx5mutAE467mPlHrvdmXtRmOyRJb3o3L/RiKc5sTFvmibT9lY2+Hj4R
    xF9Y3jEXG1krdVu0qjaORZ+mhcBRWsTuxwk4M/8ZGT4f+FprQnqjuBT/kbypLPzA
    hrnqLSMZX0GSX8l1sr1qXkWJPT4u6XGg8uowTq45m9rChjR3I1mGQArLKqqeTgvL
    kK+QrlxHv7SHRr4azsYliV9ksfc+KI5OT9DCd00GPLkpt3yfzxrvAgMBAAGjYzBh
    MA4GA1UdDwEB/wQEAwICpDAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBR2HnEV
    jtD5hcXUrFTAdjp9LzH8wzAfBgNVHSMEGDAWgBR2HnEVjtD5hcXUrFTAdjp9LzH8
    wzANBgkqhkiG9w0BAQsFAAOCAQEAGKWnC4598bWEMLbpxHOyw5GQml1uO07fceyh
    1r1qQJwz90PmUzoWQdohtf3yDlf6oDMNfoih3tQoKwYmF041Tkymj6nfy4P9aWFy
    Pvb/huFDj1FivO6wz6nXV0pDRltYQwBekYRhQXUggIU243tr0qOCEeCL76sla8JS
    eKOADkydw1hvszcTQCoP6lqNWNawROnR1K1vNO2UPaehDo0Cahgj8yq3qOePtnqb
    s53G46wx6pafIFc/c/NwfPnE97qWlkv5kviCN8jP5QJ8irf8dQRH88F5snbArlMz
    DxcFPBaQWRrZjpYAw4XOlNbbOtOZUN/AokVgEbUT7Tcc//nVJw==
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    MIIDUTCCAjmgAwIBAgIIRbT0wtvv+/cwDQYJKoZIhvcNAQELBQAwNjE0MDIGA1UE
    Awwrb3BlbnNoaWZ0LXNlcnZpY2Utc2VydmluZy1zaWduZXJAMTU5NjYyMTg4MTAe
    Fw0yMDA4MDUxMDA0NDBaFw0yMjEwMDQxMDA0NDdaMDYxNDAyBgNVBAMMK29wZW5z
    aGlmdC1zZXJ2aWNlLXNlcnZpbmctc2lnbmVyQDE1OTY2MjE4ODEwggEiMA0GCSqG
    SIb3DQEBAQUAA4IBDwAwggEKAoIBAQCcRGnYheZfLm5dtZ1gnDGj0DYgzm+oQE8B
    jdgIqRfzGT4vSmEbUP3hKtUCJJSVcafgZj/hXSOlR7OWEqEEtZt+u4NZAz6c3Qmh
    Xp2Jhou91ufqZGkWgjri/UeWOJNNUsblfoI23+CD9aQFIqQ+Qj6FSMb8mQ7E6XKs
    t17eSs5U6rxR6zyRKbM9DSNy/LfWYB5+xmvB2CDzm+D+RV/ogtYM+mEAa/ER/AVr
    uUhS24sHrvkZPKXqcpEVVgNoLIpXlYZBUFPgMiVA3ACNsHXF6sUEePhF6S2eN1lD
    FIDTSoUDoNkzlKDxI2W/WA++E3USuvU7q+53OnRK0IOU0+ybk/FbAgMBAAGjYzBh
    MA4GA1UdDwEB/wQEAwICpDAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBQXzclN
    Rs45yf1sjRTZpVZpUg1jJTAfBgNVHSMEGDAWgBR2HnEVjtD5hcXUrFTAdjp9LzH8
    wzANBgkqhkiG9w0BAQsFAAOCAQEAoS2bYSFpEV4I/Ttj8/m+oVXS9U0eDjFUt2/g
    I3R2tXumLCF5VDwy5tSmRiJp5V0KT5KM9cPsLE8Mv5Aplnaes2Ik4dstLLc8ZCBT
    eDY5vWEZS9QfUHJH/BAgrLxsd7c1EOrxrwt/mZkSa5Gd5VU7fU9V1Iv8R7mxpMXv
    GhcAYIAG7Jj2nsKgZP5WamDU7x0sF6BYctX/DwFZMeO4gIJmsY9SipOutDcK8u10
    9sgyAW8RmJlOB3cC0dqvH+n0G54oV0e9vYiswak+T3J3P9O77R65oKho0p0WcF3n
    /zyEXoj/5++5/Z8htB4raQnnsqTTCn6fVIjc1kXHZqW3jtO5qA==
    -----END CERTIFICATE-----
