apiVersion: v1
kind: ConfigMap
metadata:
  name: adguard-config
  namespace: adguard
data:
  AdGuardHome.yaml: |
    http:
      pprof:
        port: 6060
        enabled: false
      address: 0.0.0.0:3080
      session_ttl: 720h
    users:
      - name: admin
        password: $2a$10$F1t5O9cMMELXmoFgbEOYee9Uk0VLCfBI9zUZRCPGPY5NmPpjbL.Zq
    auth_attempts: 5
    block_auth_min: 15
    http_proxy: ""
    language: ""
    theme: auto
    dns:
      bind_hosts:
        - 0.0.0.0
      port: 3053
      anonymize_client_ip: false
      ratelimit: 20
      ratelimit_whitelist: []
      refuse_any: true
      upstream_dns:
        - https://dns10.quad9.net/dns-query
      upstream_dns_file: ""
      bootstrap_dns:
        - 9.9.9.10
        - 149.112.112.10
        - 2620:fe::10
        - 2620:fe::fe:10
      fallback_dns: []
      all_servers: false
      fastest_addr: false
      fastest_timeout: 1s
      allowed_clients: []
      disallowed_clients: []
      blocked_hosts:
        - version.bind
        - id.server
        - hostname.bind
      trusted_proxies:
        - 127.0.0.0/8
        - ::1/128
      cache_size: 4194304
      cache_ttl_min: 0
      cache_ttl_max: 0
      cache_optimistic: false
      bogus_nxdomain: []
      aaaa_disabled: false
      enable_dnssec: false
      edns_client_subnet:
        custom_ip: ""
        enabled: false
        use_custom: false
      max_goroutines: 300
      handle_ddr: true
      ipset: []
      ipset_file: ""
      bootstrap_prefer_ipv6: false
      upstream_timeout: 10s
      private_networks: []
      use_private_ptr_resolvers: true
      local_ptr_upstreams: []
      use_dns64: false
      dns64_prefixes: []
      serve_http3: false
      use_http3_upstreams: false
    tls:
      enabled: false
      server_name: ""
      force_https: false
      port_https: 443
      port_dns_over_tls: 853
      port_dns_over_quic: 853
      port_dnscrypt: 0
      dnscrypt_config_file: ""
      allow_unencrypted_doh: false
      certificate_chain: ""
      private_key: ""
      certificate_path: ""
      private_key_path: ""
      strict_sni_check: false
    querylog:
      ignored: []
      interval: 2160h
      size_memory: 1000
      enabled: true
      file_enabled: true
    statistics:
      ignored: []
      interval: 24h
      enabled: true
    filters:
      - enabled: true
        url: https://adguardteam.github.io/HostlistsRegistry/assets/filter_1.txt
        name: AdGuard DNS filter
        id: 1
      - enabled: false
        url: https://adguardteam.github.io/HostlistsRegistry/assets/filter_2.txt
        name: AdAway Default Blocklist
        id: 2
    whitelist_filters: []
    user_rules: []
    dhcp:
      enabled: false
      interface_name: ""
      local_domain_name: lan
      dhcpv4:
        gateway_ip: ""
        subnet_mask: ""
        range_start: ""
        range_end: ""
        lease_duration: 86400
        icmp_timeout_msec: 1000
        options: []
      dhcpv6:
        range_start: ""
        lease_duration: 86400
        ra_slaac_only: false
        ra_allow_slaac: false
    filtering:
      blocking_ipv4: ""
      blocking_ipv6: ""
      blocked_services:
        schedule:
          time_zone: UTC
        ids: []
      protection_disabled_until: null
      safe_search:
        enabled: false
        bing: true
        duckduckgo: true
        google: true
        pixabay: true
        yandex: true
        youtube: true
      blocking_mode: default
      parental_block_host: family-block.dns.adguard.com
      safebrowsing_block_host: standard-block.dns.adguard.com
      rewrites:
        - domain: registry.ipmi.gmarcy.com
          answer: 192.168.123.253
        - domain: adguard.lab.glenn4u.com
          answer: 192.168.222.253
        - domain: assisted.lab.gmarcy.com
          answer: 192.168.222.253
        - domain: console.lab.gmarcy.com
          answer: 192.168.222.253
        - domain: grafana.lab.gmarcy.com
          answer: 192.168.222.253
        - domain: matchbox.lab.gmarcy.com
          answer: 192.168.222.253
        - domain: matchbox-rpc.lab.gmarcy.com
          answer: 192.168.222.253
        - domain: metrics.lab.gmarcy.com
          answer: 192.168.222.253
        - domain: registry.lab.gmarcy.com
          answer: 192.168.222.253
        - domain: registry.lab10g.gmarcy.com
          answer: 192.168.234.253
        - domain: dymo-plug.home.glenn4u.com
          answer: 192.168.110.10
        - domain: dymo-pi.home.glenn4u.com
          answer: 192.168.110.11
        - domain: office-jet-8710.home.glenn4u.com
          answer: 192.168.110.12
        - domain: office-jet-8600.home.glenn4u.com
          answer: 192.168.110.13
        - domain: fiber-plug.home.glenn4u.com
          answer: 192.168.110.14
        - domain: gateway-plug.home.glenn4u.com
          answer: 192.168.110.15
        - domain: office-dot.home.glenn4u.com
          answer: 192.168.110.20
        - domain: bedroom-dot.home.glenn4u.com
          answer: 192.168.110.22
        - domain: brendan-dot.home.glenn4u.com
          answer: 192.168.110.23
        - domain: alcove-dot.home.glenn4u.com
          answer: 192.168.110.24
        - domain: bonus-room-dot.home.glenn4u.com
          answer: 192.168.110.25
        - domain: kitchen-dot.home.glenn4u.com
          answer: 192.168.110.26
        - domain: rachio.home.glenn4u.com
          answer: 192.168.110.31
        - domain: GatewayEABDF6.home.glenn4u.com
          answer: 192.168.110.32
        - domain: GatewayEAC220.home.glenn4u.com
          answer: 192.168.110.33
        - domain: redlink-plug.home.glenn4u.com
          answer: 192.168.110.34
        - domain: Ring-87a902.home.glenn4u.com
          answer: 192.168.110.35
        - domain: Backyard-Ring.home.glenn4u.com
          answer: 192.168.110.36
        - domain: Ring-e9c94c.home.glenn4u.com
          answer: 192.168.110.37
        - domain: MyQ-13B.home.glenn4u.com
          answer: 192.168.110.38
        - domain: kitchen-pendant1.home.glenn4u.com
          answer: 192.168.110.39
        - domain: lr-fan-light-switch.home.glenn4u.com
          answer: 192.168.110.40
        - domain: directv-smart-plug.home.glenn4u.com
          answer: 192.168.110.41
        - domain: lr-tv-smart-plug.home.glenn4u.com
          answer: 192.168.110.42
        - domain: Brendans-iPhone.home.glenn4u.com
          answer: 192.168.110.51
        - domain: Glenns-iPhone.home.glenn4u.com
          answer: 192.168.110.52
        - domain: MaryBeth-iPhone.home.glenn4u.com
          answer: 192.168.110.53
        - domain: RokuStreamingStick.home.glenn4u.com
          answer: 192.168.110.63
        - domain: LGwebOSTV.home.glenn4u.com
          answer: 192.168.110.72
        - domain: shield.home.glenn4u.com
          answer: 192.168.110.77
        - domain: Brendan-Laptop.home.glenn4u.com
          answer: 192.168.110.80
        - domain: Glenns-MBP.home.glenn4u.com
          answer: 192.168.110.82
        - domain: Mary-Beth-Yoga.home.glenn4u.com
          answer: 192.168.110.83
        - domain: MaryBeth-X1C.home.glenn4u.com
          answer: 192.168.110.85
        - domain: Glenn-L700-2.home.glenn4u.com
          answer: 192.168.110.88
        - domain: Glenn-X1C6-WiFi.home.glenn4u.com
          answer: 192.168.110.90
        - domain: Brendans-iPad.home.glenn4u.com
          answer: 192.168.110.91
        - domain: Glenns-iPad.home.glenn4u.com
          answer: 192.168.110.92
        - domain: Mary-Beths-iPad.home.glenn4u.com
          answer: 192.168.110.93
        - domain: glenn-watch.home.glenn4u.com
          answer: 192.168.110.95
        - domain: MaryBetpleWatch.home.glenn4u.com
          answer: 192.168.110.96
        - domain: Glenns-Watch.home.glenn4u.com
          answer: 192.168.110.97
        - domain: brendan-phone.home.glenn4u.com
          answer: 192.168.110.98
        - domain: MaryBeths-iPad.home.glenn4u.com
          answer: 192.168.110.99
        - domain: GMarcy-MBP-Wifi.home.glenn4u.com
          answer: 192.168.110.101
        - domain: net-111-plug.home.glenn4u.com
          answer: 192.168.110.114
        - domain: net-222-plug.home.glenn4u.com
          answer: 192.168.110.115
        - domain: net-234-plug.home.glenn4u.com
          answer: 192.168.110.116
        - domain: net-123-plug.home.glenn4u.com
          answer: 192.168.110.117
        - domain: khadas-edge2.home.glenn4u.com
          answer: 192.168.110.145
        - domain: server0-plug.home.glenn4u.com
          answer: 192.168.110.200
        - domain: server1-plug.home.glenn4u.com
          answer: 192.168.110.201
        - domain: server2-plug.home.glenn4u.com
          answer: 192.168.110.202
        - domain: server3-plug.home.glenn4u.com
          answer: 192.168.110.203
        - domain: server4-plug.home.glenn4u.com
          answer: 192.168.110.204
        - domain: server5-plug.home.glenn4u.com
          answer: 192.168.110.205
        - domain: server6-plug.home.glenn4u.com
          answer: 192.168.110.206
        - domain: server7-plug.home.glenn4u.com
          answer: 192.168.110.207
        - domain: lab-pi-wifi.home.glenn4u.com
          answer: 192.168.110.216
        - domain: p340-wifi.home.glenn4u.com
          answer: 192.168.110.220
        - domain: router.home.glenn4u.com
          answer: 192.168.111.1
        - domain: GS1910-24.home.glenn4u.com
          answer: 192.168.111.2
        - domain: SXR80.home.glenn4u.com
          answer: 192.168.111.3
        - domain: SXS80.home.glenn4u.com
          answer: 192.168.111.4
        - domain: GS305E.home.glenn4u.com
          answer: 192.168.111.5
        - domain: GS108E.home.glenn4u.com
          answer: 192.168.111.6
        - domain: GS110EMX.home.glenn4u.com
          answer: 192.168.111.7
        - domain: XGS1250-12.home.glenn4u.com
          answer: 192.168.111.8
        - domain: QSW-M2108R-2C.home.glenn4u.com
          answer: 192.168.111.9
        - domain: amazon-ad68ca1c7.home.glenn4u.com
          answer: 192.168.111.21
        - domain: SmartThingsWifi.home.glenn4u.com
          answer: 192.168.111.30
        - domain: hue-hub.home.glenn4u.com
          answer: 192.168.111.38
        - domain: lutron-02c1073d.home.glenn4u.com
          answer: 192.168.111.39
        - domain: directv-hub.home.glenn4u.com
          answer: 192.168.111.60
        - domain: office-tv.home.glenn4u.com
          answer: 192.168.111.61
        - domain: BedroomRoku.home.glenn4u.com
          answer: 192.168.111.62
        - domain: RokuUltraLR.home.glenn4u.com
          answer: 192.168.111.64
        - domain: RokuUltraBonus.home.glenn4u.com
          answer: 192.168.111.65
        - domain: DIRECTV-HR54-C92.home.glenn4u.com
          answer: 192.168.111.66
        - domain: Chromecast-Ultra.home.glenn4u.com
          answer: 192.168.111.67
        - domain: Bonus-Chromecast-Ultra.home.glenn4u.com
          answer: 192.168.111.68
        - domain: playstation4.home.glenn4u.com
          answer: 192.168.111.69
        - domain: bonus-soundbar.home.glenn4u.com
          answer: 192.168.111.70
        - domain: Bonus-Apple4k.home.glenn4u.com
          answer: 192.168.111.71
        - domain: lr-lg-tv.home.glenn4u.com
          answer: 192.168.111.73
        - domain: Caavo-0F-00-65.home.glenn4u.com
          answer: 192.168.111.74
        - domain: XboxOne.home.glenn4u.com
          answer: 192.168.111.75
        - domain: switch.home.glenn4u.com
          answer: 192.168.111.76
        - domain: Wii.home.glenn4u.com
          answer: 192.168.111.78
        - domain: firetv.home.glenn4u.com
          answer: 192.168.111.79
        - domain: bonus-lg-4k-disc-player.home.glenn4u.com
          answer: 192.168.111.80
        - domain: Brendan-PC.home.glenn4u.com
          answer: 192.168.111.81
        - domain: Glenn-X1C.home.glenn4u.com
          answer: 192.168.111.84
        - domain: Glenn-L700.home.glenn4u.com
          answer: 192.168.111.87
        - domain: Glenn-One.home.glenn4u.com
          answer: 192.168.111.88
        - domain: Glenn-L700-3.home.glenn4u.com
          answer: 192.168.111.89
        - domain: GLENN-X1C6.home.glenn4u.com
          answer: 192.168.111.90
        - domain: GMarcy-MBP.home.glenn4u.com
          answer: 192.168.111.101
        - domain: Glenn-MBA.home.glenn4u.com
          answer: 192.168.111.102
        - domain: glenn-mbp.home.glenn4u.com
          answer: 192.168.111.103
        - domain: MacAllanCloud.home.glenn4u.com
          answer: 192.168.111.111
        - domain: nuc.home.glenn4u.com
          answer: 192.168.111.210
        - domain: nuc8.com.home.glenn4u.com
          answer: 192.168.111.212
        - domain: nuc10.home.glenn4u.com
          answer: 192.168.111.214
        - domain: p340.home.glenn4u.com
          answer: 192.168.111.220
        - domain: p360.home.glenn4u.com
          answer: 192.168.111.221
        - domain: RamseyHillCloud.home.glenn4u.com
          answer: 192.168.111.222
        - domain: netsvcs.home.glenn4u.com
          answer: 192.168.111.253
        - domain: mikrotik.ipmi.gmarcy.com
          answer: 192.168.123.2
        - domain: glenn-mbp.ipmi.gmarcy.com
          answer: 192.168.123.103
        - domain: server0.ipmi.gmarcy.com
          answer: 192.168.123.200
        - domain: server1.ipmi.gmarcy.com
          answer: 192.168.123.201
        - domain: server2.ipmi.gmarcy.com
          answer: 192.168.123.202
        - domain: server3.ipmi.gmarcy.com
          answer: 192.168.123.203
        - domain: server4.ipmi.gmarcy.com
          answer: 192.168.123.204
        - domain: server5.ipmi.gmarcy.com
          answer: 192.168.123.205
        - domain: server6.ipmi.gmarcy.com
          answer: 192.168.123.206
        - domain: server7.ipmi.gmarcy.com
          answer: 192.168.123.207
        - domain: nuc.ipmi.gmarcy.com
          answer: 192.168.123.210
        - domain: nuc8.ipmi.gmarcy.com
          answer: 192.168.123.212
        - domain: nuc10.ipmi.gmarcy.com
          answer: 192.168.123.214
        - domain: p360.ipmi.gmarcy.com
          answer: 192.168.123.221
        - domain: RamseyHillCloud.ipmi.gmarcy.com
          answer: 192.168.123.222
        - domain: netsvcs.ipmi.gmarcy.com
          answer: 192.168.123.253
        - domain: router.lab.gmarcy.com
          answer: 192.168.222.1
        - domain: gmarcy-mbp.lab.gmarcy.com
          answer: 192.168.222.101
        - domain: glenn-mbp.lab.gmarcy.com
          answer: 192.168.222.103
        - domain: server0.lab.gmarcy.com
          answer: 192.168.222.200
        - domain: server1.lab.gmarcy.com
          answer: 192.168.222.201
        - domain: server2.lab.gmarcy.com
          answer: 192.168.222.202
        - domain: server3.lab.gmarcy.com
          answer: 192.168.222.203
        - domain: server4.lab.gmarcy.com
          answer: 192.168.222.204
        - domain: server5.lab.gmarcy.com
          answer: 192.168.222.205
        - domain: server6.lab.gmarcy.com
          answer: 192.168.222.206
        - domain: server7.lab.gmarcy.com
          answer: 192.168.222.207
        - domain: nuc.lab.gmarcy.com
          answer: 192.168.222.210
        - domain: nuc8.lab.gmarcy.com
          answer: 192.168.222.212
        - domain: nuc10.lab.gmarcy.com
          answer: 192.168.222.214
        - domain: lab-pi.lab.gmarcy.com
          answer: 192.168.222.216
        - domain: p340.lab.gmarcy.com
          answer: 192.168.222.220
        - domain: p360.lab.gmarcy.com
          answer: 192.168.222.221
        - domain: RamseyHillCloud.lab.gmarcy.com
          answer: 192.168.222.222
        - domain: p3.lab.gmarcy.com
          answer: 192.168.222.223
        - domain: edge2a.lab.gmarcy.com
          answer: 192.168.222.230
        - domain: edge2b.lab.gmarcy.com
          answer: 192.168.222.231
        - domain: edge2c.lab.gmarcy.com
          answer: 192.168.222.232
        - domain: may0.lab.gmarcy.com
          answer: 192.168.222.240
        - domain: may1.lab.gmarcy.com
          answer: 192.168.222.241
        - domain: may2.lab.gmarcy.com
          answer: 192.168.222.242
        - domain: may3.lab.gmarcy.com
          answer: 192.168.222.243
        - domain: um690.lab.gmarcy.com
          answer: 192.168.222.245
        - domain: th80a.lab.gmarcy.com
          answer: 192.168.222.246
        - domain: th80b.lab.gmarcy.com
          answer: 192.168.222.247
        - domain: th80c.lab.gmarcy.com
          answer: 192.168.222.248
        - domain: netsvcs.lab.gmarcy.com
          answer: 192.168.222.253
        - domain: es-16-xg.lab10g.gmarcy.com
          answer: 192.168.234.2
        - domain: server0.lab10g.gmarcy.com
          answer: 192.168.234.200
        - domain: server1.lab10g.gmarcy.com
          answer: 192.168.234.201
        - domain: server2.lab10g.gmarcy.com
          answer: 192.168.234.202
        - domain: server3.lab10g.gmarcy.com
          answer: 192.168.234.203
        - domain: server4.lab10g.gmarcy.com
          answer: 192.168.234.204
        - domain: server5.lab10g.gmarcy.com
          answer: 192.168.234.205
        - domain: server6.lab10g.gmarcy.com
          answer: 192.168.234.206
        - domain: server7.lab10g.gmarcy.com
          answer: 192.168.234.207
        - domain: nuc.lab10g.gmarcy.com
          answer: 192.168.234.210
        - domain: nuc8.lab10g.gmarcy.com
          answer: 192.168.234.212
        - domain: nuc10.lab10g.gmarcy.com
          answer: 192.168.234.214
        - domain: RamseyHillCloud.lab10g.gmarcy.com
          answer: 192.168.234.222
        - domain: netsvcs.lab10g.gmarcy.com
          answer: 192.168.234.253
      safebrowsing_cache_size: 1048576
      safesearch_cache_size: 1048576
      parental_cache_size: 1048576
      cache_time: 30
      filters_update_interval: 24
      blocked_response_ttl: 10
      filtering_enabled: true
      parental_enabled: false
      safebrowsing_enabled: false
      protection_enabled: true
    clients:
      runtime_sources:
        whois: true
        arp: true
        rdns: true
        dhcp: true
        hosts: true
      persistent: []
    log:
      file: ""
      max_backups: 0
      max_size: 100
      max_age: 3
      compress: false
      local_time: false
      verbose: false
    os:
      group: ""
      user: ""
      rlimit_nofile: 0
    schema_version: 27
