apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: adguard

resources:
  - configmap.yaml

helmCharts:
  - name: app-template
    repo: https://bjw-s.github.io/helm-charts/
    releaseName: adguard
    namespace: adguard
    version: 2.4.0
    valuesInline:
      controllers:
        main:
          initContainers:
            copy:
              image:
                repository: busybox
                tag: 1.36
              command:
                - /bin/sh
                - -c
                - cp /config/*.yaml /opt/adguardhome/conf/
          containers:
            main:
              image:
                repository: adguard/adguardhome
                tag: v0.107.43
                pullPolicy: IfNotPresent
              probes:
                liveness:
                  enabled: false
                readiness:
                  enabled: false
                startup:
                  enabled: false
              securityContext:
                privileged: true
      defaultPodOptions:
        automountServiceAccountToken: false
      persistence:
        data:
          enabled: true
          type: persistentVolumeClaim
          accessMode: ReadWriteOnce
          size: 1Gi
          globalMounts:
            - path: /opt/adguardhome/work
              subPath: work
            - path: /opt/adguardhome/conf
              subPath: conf
        conf:
          enabled: true
          type: configMap
          name: adguard-config
          globalMounts:
            - path: /config
      service:
        main:
          ports:
            http:
              port: 3080
        dns:
          controller: main
          ports:
            dns:
              port: 3053
              protocol: UDP
      ingress:
        main:
          enabled: true
          annotations:
            nginx.ingress.kubernetes.io/backend-protocol: HTTP
            nginx.ingress.kubernetes.io/ssl-redirect: "false"
          className: nginx
          hosts:
            # kustomize will replace this with the cluster ip address
            - host: adguard.xxx.xxx.xxx.xxx.nip.io
              paths:
                - path: /
                  service:
                    name: main
