apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: topolvm-system

resources:
  - namespace.yaml

helmCharts:
  - name: topolvm
    repo: https://topolvm.github.io/topolvm/
    releaseName: topolvm
    namespace: topolvm-system
    version: 13.0.0
    includeCRDs: true
    valuesInline:
      controller:
        replicaCount: 1
        storageCapacityTracking:
          enabled: false
      lvmd:
        deviceClasses:
          - name: ssd
            volume-group: csi-lvm
            default: true
            spare-gb: 10
      podSecurityPolicy:
        create: false
      scheduler:
        enabled: false
      storageClasses:
        - name: topolvm-provisioner
          storageClass:
            isDefaultClass: true
            allowVolumeExpansion: true
            fsType: xfs
      webhook:
        podMutatingWebhook:
          enabled: true

patches:
  - patch: |-
      - op: replace
        path: /spec/duration
        value: 8760h0m0s
    target:
      group: cert-manager.io
      version: v1
      kind: Certificate
      name: topolvm-mutatingwebhook
  - patch: |-
      - op: replace
        path: /spec/duration
        value: 87600h0m0s
    target:
      group: cert-manager.io
      version: v1
      kind: Certificate
      name: topolvm-webhook-ca
