apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: ethernet
  namespace: nmstate
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  desiredState:
    interfaces:
    - name: enp2s0
      type: ethernet
      state: up
      ipv4:
        address:
        - ip: 192.168.222.253
          prefix-length: 24
        enabled: true
    - name: enp3s0
      type: ethernet
      state: up
      ipv4:
        address:
        - ip: 192.168.111.253
          prefix-length: 21
        enabled: true
    - name: enp4s0
      type: ethernet
      state: up
      ipv4:
        address:
        - ip: 192.168.123.253
          prefix-length: 24
        enabled: true
