app:
  label: cert-manager
  name: cert-manager
cluster:
  name: nuc8-cluster
destination:
  namespace: cert-manager
  server: https://kubernetes.default.svc
project:
  name: default
source:
  path: cert-manager/overlays/nuc8-cluster
  repoURL: https://github.com/gmarcy/homelab-argocd.git
  targetRevision: HEAD
