app:
  label: olm
  name: olm
cluster:
  name: netsvcs-cluster
destination:
  namespace: olm
  server: https://192.168.222.253.nip.io:6443
project:
  name: default
source:
  path: olm/overlays/netsvcs-cluster
  repoURL: https://github.com/gmarcy/homelab-argocd.git
  targetRevision: HEAD
