app:
  label: cert-manager
  name: cert-manager
cluster:
  name: nuc10-cluster
destination:
  namespace: cert-manager
  server: https://192.168.222.214.nip.io:6443
project:
  name: default
source:
  path: cert-manager/overlays/nuc10-cluster
  repoURL: https://github.com/gmarcy/homelab-argocd.git
  targetRevision: HEAD
