app:
  label: grafana-agent
  name: grafana-agent
cluster:
  name: netsvcs-cluster
destination:
  namespace: grafana-agent
  server: https://192.168.222.253.nip.io:6443
project:
  name: default
source:
  path: grafana-agent/overlays/netsvcs-cluster
  repoURL: https://github.com/gmarcy/homelab-argocd.git
  targetRevision: HEAD
