---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: dnsmasq-controller-dhcp
  namespace: dnsmasq-dhcp
  labels:
    app: dnsmasq-controller-dhcp
spec:
  selector:
    matchLabels:
      app: dnsmasq-controller-dhcp
  template:
    metadata:
      labels:
        app: dnsmasq-controller-dhcp
    spec:
      hostNetwork: true
      containers:
      - name: dnsmasq-dhcp
        image: ghcr.io/gmarcy/dnsmasq-controller:2023-11-26-18-41-44
        securityContext:
          capabilities:
            add: ["NET_ADMIN"]
        args:
        - --watch-namespace=$(NAMESPACE)
        - --metrics-addr=:0
        - --dhcp
        - --
        - --interface=enp2s0
        - --interface=enp3s0
        - --interface=enp4s0
        - --interface=enp5s0
        - --except-interface=lo
        - --no-resolv
        - --log-queries
        - --log-dhcp
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        resources:
          limits:
            cpu: 100m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
      priorityClassName: system-node-critical
      serviceAccountName: dnsmasq-controller-dhcp
      terminationGracePeriodSeconds: 10
      tolerations:
      - effect: NoSchedule
        operator: Exists
      - effect: NoExecute
        operator: Exists
      - key: CriticalAddonsOnly
        operator: Exists
