---

apiVersion: dnsmasq.kvaps.cf/v1beta1
kind: DnsmasqOptions
metadata:
  name: options
  namespace: dnsmasq-dhcp
spec:
  controller: ""
  options:
  - key: dhcp-range
    values:
    - set:net111
    - 192.168.111.120
    - 192.168.111.199
    - 24h
  - key: dhcp-range
    values:
    - set:net123
    - 192.168.123.120
    - 192.168.123.199
    - 24h
  - key: dhcp-range
    values:
    - set:net222
    - 192.168.222.120
    - 192.168.222.199
    - 24h
  - key: dhcp-range
    values:
    - set:net234
    - 192.168.234.120
    - 192.168.234.199
    - 24h
  - key: dhcp-match
    values:
    - set:ipxe
    - "175"
  - key: dhcp-boot
    values:
    - tag:ipxe
    - ipxe/netboot.xyz.kpxe
    - 192.168.222.210
  - key: dhcp-match
    values:
    - set:efi
    - option:client-arch
    - "7"
  - key: dhcp-match
    values:
    - set:efi
    - option:client-arch
    - "9"
  - key: dhcp-match
    values:
    - set:efi
    - option:client-arch
    - "11"
  - key: dhcp-boot
    values:
    - tag:efi
    - tag:!ipxe
    - ipxe/netboot.xyz.efi
  - key: dhcp-boot
    values:
    - tag:net222
    - ipxe/netboot.xyz.kpxe
    - 192.168.222.210
