---

apiVersion: dnsmasq.kvaps.cf/v1beta1
kind: DnsmasqOptions
metadata:
  name: options
  namespace: dnsmasq-dhcp
spec:
  controller: ""
  options:
  - key: dhcp-range
    values:
    - set:net111
    - 192.168.110.120
    - 192.168.110.199
    - 24h
  - key: dhcp-range
    values:
    - set:net123
    - 192.168.123.120
    - 192.168.123.199
    - 24h
  - key: dhcp-range
    values:
    - set:net222
    - 192.168.222.120
    - 192.168.222.199
    - 24h
  - key: dhcp-range
    values:
    - set:net234
    - 192.168.234.120
    - 192.168.234.199
    - 24h
