apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dnsmasq-dhcp

resources:
  - https://github.com/gmarcy/dnsmasq-controller/config/crd/bases
  - https://github.com/gmarcy/dnsmasq-controller/config/rbac
  - deployment.yaml
  - dhcp_hosts.yaml
  - dhcp_options.yaml
  - dnsmasq_options.yaml
