---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dnsmasq-controller-dhcp
rules:
- apiGroups:
  - dnsmasq.kvaps.cf
  resources:
  - dhcphosts
  - dhcpoptions
  - dnshosts
  - dnsmasqoptions
  verbs:
  - get
  - list
  - watch
