apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: netbootxyz-setup
    literals:
      - |
        setup-menus.sh=rm -rf /config/menus
        cp -r /config/buildout /config/menus
        mv /config/buildout /config/menus/remote
        mkdir -p /config/menus/local /config/nginx/site-confs
        touch /config/nginx/site-confs/default

helmCharts:
  - name: app-template
    repo: https://bjw-s.github.io/helm-charts/
    releaseName: netbootxyz
    namespace: netbootxyz
    version: 2.4.0
    valuesInline:
      controllers:
        main:
          type: statefulset
          initContainers:
            builder:
              image:
                repository: ghcr.io/gmarcy/netboot.xyz-builder
                tag: latest
            setup:
              image:
                repository: busybox
                tag: 1.36
              command:
                - /bin/sh
                - -x
                - /setup/setup-menus.sh
          containers:
            main:
              image:
                repository: ghcr.io/netbootxyz/netbootxyz
                tag: 0.7.0-nbxyz2
              env:
                TZ: UTC
              securityContext:
                privileged: true
          statefulset:
            volumeClaimTemplates:
              - name: config
                accessMode: ReadWriteOnce
                size: 2Gi
                globalMounts:
                  - path: /config
              - name: assets
                accessMode: ReadWriteOnce
                size: 2Gi
                globalMounts:
                  - path: /assets
      defaultPodOptions:
        hostNetwork: true
      persistence:
        setup:
          enabled: true
          type: configMap
          name: netbootxyz-setup
          mountPath: "-"
      service:
        main:
          ports:
            http:
              port: 3000
        tftp:
          enabled: true
          primary: false
          controller: main
          type: NodePort
          ports:
            tftp:
              enabled: true
              primary: false
              port: 69
              targetPort: 69
              protocol: UDP
      ingress:
        main:
          enabled: true
          className: nginx
          hosts:
            # kustomize will replace this with the cluster ip address
            - host: netbootxyz.xxx.xxx.xxx.xxx.nip.io
              paths:
                - path: /
                  service:
                    name: main
          tls:
            # kustomize will replace this with the cluster ip address
            - hosts: [netbootxyz.xxx.xxx.xxx.xxx.nip.io]

patches:
  - patch: |-
      - op: remove
        path: /spec/template/spec/containers/0/volumeMounts/2
      - op: remove
        path: /spec/template/spec/initContainers/0/volumeMounts/2
      - op: remove
        path: /spec/template/spec/initContainers/0/volumeMounts/0
      - op: replace
        path: /spec/template/spec/initContainers/0/volumeMounts/0/mountPath
        value: /buildout
    target:
      group: apps
      version: v1
      kind: StatefulSet
      name: netbootxyz
