apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: nuc10-cluster
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  generators:
  - git:
      files:
      - path: resources/configurations/nuc10-cluster/*-config.yaml
      repoURL: https://github.com/gmarcy/homelab-argocd.git
      requeueAfterSeconds: 20
      revision: ""
      template:
        metadata: {}
        spec:
          destination: {}
          project: ""
  syncPolicy: {}
  template:
    metadata:
      name: nuc10-cluster-{{ userGivenName }}
      namespace: argocd
      labels:
        app.kubernetes.io/name: '{{ appName }}'
    spec:
      destination:
        namespace: '{{ destNamespace }}'
        server: '{{ destServer }}'
      ignoreDifferences:
      - group: argoproj.io
        jsonPointers:
        - /status
        kind: Application
      project: nuc10-cluster
      source:
        path: '{{ srcPath }}'
        repoURL: '{{ srcRepoURL }}'
        targetRevision: '{{ srcTargetRevision }}'
      syncPolicy:
        automated:
          allowEmpty: true
          prune: true
          selfHeal: true
