app:
  label: topolvm
  name: topolvm
cluster:
  name: netsvcs-cluster
destination:
  namespace: topolvm-system
  server: https://kubernetes.default.svc
project:
  name: default
source:
  path: topolvm/overlays/netsvcs-cluster
  repoURL: https://github.com/gmarcy/homelab-argocd.git
  targetRevision: HEAD
