appName: nmstate
userGivenName: nmstate
destNamespace: nmstate
destServer: https://192.168.222.253.nip.io:6443
srcPath: deployments/netsvcs-cluster/nmstate
srcRepoURL: https://github.com/gmarcy/homelab-argocd.git
srcTargetRevision: ''
labels: null
annotations: null
