app:
  label: grafana-agent
  name: grafana-agent
cluster:
  name: nuc8-cluster
destination:
  namespace: grafana-agent
  server: https://kubernetes.default.svc
project:
  name: default
source:
  path: grafana-agent/overlays/nuc8-cluster
  repoURL: https://github.com/gmarcy/homelab-argocd.git
  targetRevision: HEAD
