apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: "argocd.192.168.222.253.nip.io"
      - op: add
        path: /spec/tls/0/hosts/-
        value: "argocd.192.168.222.253.nip.io"
    target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
