appName: netbootxyz
userGivenName: netbootxyz
destNamespace: default
destServer: https://192.168.222.214.nip.io:6443
srcPath: resources/overlays/nuc10-cluster/netbootxyz
srcRepoURL: https://github.com/gmarcy/homelab-argocd.git
srcTargetRevision: ''
labels: null
annotations: null
