app:
  label: metallb
  name: metallb
cluster:
  name: no-cluster
destination:
  namespace: metallb-system
  server: https://kubernetes.default.svc
project:
  name: default
source:
  path: metallb/overlays/no-cluster
  repoURL: https://github.com/gmarcy/homelab-argocd.git
  targetRevision: HEAD
