app:
  label: nmstate
  name: nmstate
cluster:
  name: nuc10-cluster
destination:
  namespace: nmstate
  server: https://192.168.222.214.nip.io:6443
project:
  name: default
source:
  path: nmstate/overlays/nuc10-cluster
  repoURL: https://github.com/gmarcy/homelab-argocd.git
  targetRevision: HEAD
