apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

resources:
  - argocd-cluster-app-set.yaml
  - argocd-cluster-project.yaml
  - netsvcs-cluster-app-set.yaml
  - netsvcs-cluster-project.yaml
  - nuc10-cluster-app-set.yaml
  - nuc10-cluster-project.yaml
