apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../apps/matchbox

patches:
  - patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: matchbox.192.168.222.214.nip.io
    target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: matchbox
  - patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: matchbox-rpc.192.168.222.214.nip.io
      - op: add
        path: /spec/tls/0/hosts/-
        value: "matchbox-rpc.192.168.222.214.nip.io"
    target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: matchbox-rpc
