app:
  label: kube-vip
  name: kube-vip
cluster:
  name: netsvcs-cluster
destination:
  namespace: kube-system
  server: https://kubernetes.default.svc
project:
  name: default
source:
  path: kube-vip/overlays/netsvcs-cluster
  repoURL: https://github.com/gmarcy/homelab-argocd.git
  targetRevision: HEAD
